### ISSUE TITLE
"sar_alias" does not accept commands in quotation marks.

### ISSUE THREAD

**Issue by Cant-Even** [p2sr/SourceAutoRecord#10]
`sar_alias` does not accept commands within quotation marks. This is critical as it prevents you from putting more than one command in a SAR alias. When running the alias with commands in it, the game simply outputs in console `Unknown command "<command(s)>"`, even when the command(s) are perfectly valid.

Reproduction steps:
1.) Load Portal 2, then load SAR.
2.) Make an alias with quotation marks using `sar_alias`. Example: `sar_alias bug "echo bug"`
3.) Run the alias. Example: `bug`
4.) Note that the console output is `Unknown command "echo bug"`, even though `echo bug` is a perfectly valid command.

I also sent this in #sar-discussion on the Portal 2 Discord server.

UPDATE: The bug was introduced in version 1.12.3-pre4, so my best guess is that something in the Portal 2 update may have broken this?

**Comment by mlugg** [comment]
Fixed in f55ca77
