### ISSUE TITLE
sar_hud_set_text_color echoes wrong hint

### ISSUE THREAD

**Issue by soni801** [p2sr/SourceAutoRecord#11]
**Description**
When typing `sar_hud_set_text_color` in console, the console returns the hint for `sar_hud_set_text` instead of its own hint. [Screenshot](https://i.imgur.com/6EmK4xA.png).

**Expected behaviour**
`sar_hud_set_text_color` returns a hint that explains what it does.

**Environment**
- OS: Windows 10 Home 21H1 (Build 19043.985)
- SAR version: [1.12.3-pre4](https://i.imgur.com/zQdi7S4.png)
- Portal 2 version: Steam Latest release

**Comment by mlugg** [comment]
fixed in 29794b4
