### ISSUE TITLE
[BUG] crash on linux while loading

### ISSUE THREAD

**Issue by Hanuko33** [p2sr/SourceAutoRecord#117]
I do "plugin_load sar" and it crashes, i have no idea why

**Comment by Hanuko33** [comment]
there are no logs =(

**Comment by Krzyhau** [comment]
What version did you install? Older versions of SAR stopped working on Linux since the latest Portal 2 update. Make sure to try the [latest prerelease](https://github.com/p2sr/SourceAutoRecord/releases/tag/1.12.8-pre6).

**Comment by Hanuko33** [comment]
oh, i used the "newest realese" which isnt the prerealese, ill try it tomorrow if i will have time (sorry for poor english)

**Comment by Hanuko33** [comment]
works! THANKS!
