### ISSUE TITLE
`end` speedrun rule doesn't work in Mel

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/SourceAutoRecord#122]
Since Mel presumably uses a different mechanism to transition between levels, our `Engine::ChangeLevel` hook doesn't get triggered, which means `engine->isLevelTransition` is never set to true which means the map end rules are never tested.

The other possibility is that Mel somehow overrides the function, or has a different offset, which I think is unlikely.

**Comment by mlugg** [comment]
Needs confirming: how does Mel transition between maps? My guess is that it's running `changelevel2` manually (the function AMJ mentions just runs that command). If so, we should just hook that command instead (as well as `changelevel`).

**Comment by ThisAMJ** [comment]
By the looks of things, it just uses `changelevel`! More specifically, the entity input `end_command.Command(changelevel <next map>)`
