### ISSUE TITLE
SAR instantly crashing on steam deck

### ISSUE THREAD

**Issue by gingerphoenix10** [p2sr/SourceAutoRecord#128]
For some reason, I have installed the latest version of sar on steam deck, but every time I try and load the plugin, it crashes. I have tried it in both the Portal 2 folder and portal2 folder with and without srconfigs and I’ve tried every single portal 2 beta, but nothing seems to work.

**Comment by PortalRex** [comment]
Download latest pre release as it fixes crash on linux

**Comment by ThisAMJ** [comment]
By 'latest version of SAR,' do you mean full release or pre-release? The Steam Deck runs on the Linux version, which works on pre-release (1.12.8-pre6) but not full release (1.12.7)

**Comment by gingerphoenix10** [comment]
Ah yeah, I didn’t try the pre-release. Thank you
