### ISSUE TITLE
[TAS parser] Even amount of numbers in movement or angle field is wrongly considered valid

### ISSUE THREAD

**Issue by RainbowwPhoenixx** [p2sr/SourceAutoRecord#155]
```
version 6
start now

0>0 0 0 0||||

+50>
```
is a valid script, when it really shouldn't be.
Only the last pair of numbers will take effect.

**Comment by Krzyhau** [comment]
Resolved by 64137af. Check if everything's fine and then we can close this.

**Comment by Krzyhau** [comment]
No idea why this issue remained open for this long. Closing.
