### ISSUE TITLE
sar_pp_hud 1 doesn't work for atlas or pbody

### ISSUE THREAD

**Issue by Prince-Piplup** [p2sr/SourceAutoRecord#157]

**Comment by ThisAMJ** [comment]
Well which is it, atlas (blue) or pbody (orange)?

**Comment by ThisAMJ** [comment]
To elaborate on this, **pbody**'s pp_hud shows "No portal gun". There are a multitude of reasons this probably won't be fixed, namely the feature being at least 90% on the server
