### ISSUE TITLE
 Portal 1 build 3420 doesnt work with SourceAutoRecord

### ISSUE THREAD

**Issue by ianSteam** [p2sr/SourceAutoRecord#195]
When i try to load SourceAutoRecord on Portal 1 build 3420 it crashes the game.

**Comment by JaioCG** [comment]
This version of SAR is meant specifically for Portal 2, with support for other games being removed. If you want an old version of SAR that works with Portal, HL2, and other games, go here: https://github.com/blenderiste09/SourceAutoRecord

**Comment by ThatFridgeFella** [comment]
best thing would be to use SST which is a tool more specific for Portal 1, you can join their discord @ https://discord.gg/zE75dN6B and find an install link and info about it there.
