### ISSUE TITLE
allow for multiple maps in a category definition

### ISSUE THREAD

**Issue by JaioCG** [p2sr/SourceAutoRecord#208]
Mainly useful for Mel CM mtriggers where there are both the normal and advanced versions of each map. I did a little bit of testing and the mtriggers should all* work cross-map, meaning the only thing stopping only needing one set of mtriggers would be the category definitions themselves:

```sar_speedrun_cc_start "Concepts" map=st_a3_concepts map=sp_a3_concepts action=split```

Basically just allow two (or more teehee) maps in a category definition. Running a category can already be done via

```sar_on_load cond "var:__mtriggers_enable=1 & (map=st_a3_concepts | map=sp_a3_concepts)" sar_speedrun_category "Concepts"```

so maybe the syntax could be similar idk.

**Comment by ThisAMJ** [comment]
The only question I have is how rule hierarchy should handle this i.e.

`action=split` on category is overridden by `action=start` on rule, should the same be true for maps? i would think so

e.g. if you wanted a category that was 2 maps long, i guess?
`map=map_a map=map_b` category
`rule load action=start map=map_a` starts it only on map a. its *really* situational to use this

**Comment by JaioCG** [comment]
Implemented in 3a6c09317916923ece4b461235d145bfa621a9cf

**Comment by ThisAMJ** [comment]
Implemented again in 91c2f960463dc68dcf29d49c3eeecbd0071d0713

**Comment by JaioCG** [comment]
Neither commit works properly, shows
![image](https://github.com/p2sr/SourceAutoRecord/assets/67981958/13c31f39-7b96-4318-b656-c9c447a90541)
 when attempting to play

**Comment by ThisAMJ** [comment]
skill issue
<img width="596" alt="Screenshot-2023-11-23_11-58-53" src="https://github.com/p2sr/SourceAutoRecord/assets/69196954/7a7b1449-ffc2-41cf-ab77-b98d4474338a">
