### ISSUE TITLE
cant use sar in portal 2

### ISSUE THREAD

**Issue by Al5x404-cat** [p2sr/SourceAutoRecord#214]
ok, i put sar into the folder, but it wont load, i need help because i really wanna get my inputs shown. how do i fix it? ps. i have the sar.dll file.

**Comment by PortalRex** [comment]
Join the discord and post in the help channel. https://discord.com/invite/p2sr

**Comment by Al5x404-cat** [comment]
> Join the discord and post in the help channel. https://discord.com/invite/p2sr

that was fast. thank you tho

**Comment by Al5x404-cat** [comment]
oh my god im such an idiot. it was sar(1).dll
i just removed the (1) and now i can
play
BUT IT CRAS- nvm i see it on the page
