### ISSUE TITLE
Rewrite LiveSplit autosplliter in AutoSplitterRuntime

### ISSUE THREAD

**Issue by JaioCG** [p2sr/SourceAutoRecord#223]
[LiveSplit One](https://github.com/LiveSplit/LiveSplitOne) (the rewrite of LiveSplit) has autosplitter support now in the form of the new auto splitting runtime (ASR), with these new autosplitters being written in Rust rather than C#. Eventually the current autosplitter will have to be rewritten as I don't think AutoSplitting Language (ASL) will be supported once LiveSplit One releases, plus with LiveSplit One being cross platform, it'll give the opportunity for Linux users to autosplit easily without having to jump through hoops with Wine and Proton.

ASR Resources:
https://github.com/LiveSplit/obs-livesplit-one
https://livesplit.org/asr/asr/

**Comment by ThisAMJ** [comment]
https://github.com/p2sr/sar-auto-splitter

**Comment by JaioCG** [comment]
Merged into LiveSplit.Autosplitters https://github.com/LiveSplit/LiveSplit.AutoSplitters/commit/3a363fa973a1ff28d1050bfdb84cc6b3f73a8575
