### ISSUE TITLE
Coop point_viewcontrol reset fix patched betsrighter

### ISSUE THREAD

**Issue by Alex-Marek** [p2sr/SourceAutoRecord#231]
Disabling the point_viewcontrol at the end of the Wakeup patches Betsrighter. 
Could probably get away with just making an exception for the point_viewcontrol disable just for Wakeup considering that right when you load into the next map it resolves the see through wall part of the bug (the only thing we really cared about patching). 

Discord messages that found this (I also tested it to make sure the person wasn't just doing Betsrighter incorrectly):
https://discord.com/channels/146404426746167296/730456562337972248/1233483543355719822

**Comment by ThisAMJ** [comment]
Fixed by 0b4c5d0
