### ISSUE TITLE
Game crashes at plugin load.

### ISSUE THREAD

**Issue by AngelBePro** [p2sr/SourceAutoRecord#245]
When I try to start the game, with srconfig, the game crashesh. I tried to load the plugin after the game has started, but it still crashes. On Linux. Don't know needed logs so you tell me :P.

**Comment by AngelBePro** [comment]
Also running latest SAR since at lauch it auto updates.

**Comment by ThisAMJ** [comment]
Known issue, will be fixed in next release which will be happening momentarily

**Comment by Pinuaple** [comment]
This is happening again

**Comment by ThisAMJ** [comment]
When did you last update sar (last modified date of the dll)

**Comment by ThisAMJ** [comment]
Oh this is a different person
