### ISSUE TITLE
sar_tas_protocol_server breaks after multiple uses

### ISSUE THREAD

**Issue by rudkoLA** [p2sr/SourceAutoRecord#255]
on the first time you enable it, it works fine but if you use it again the vscode extension won't be able to connect to it anymore unless you restart the game

**Comment by Krzyhau** [comment]
Should be fixed by b56f32f

**Comment by ThisAMJ** [comment]
@rudkoLA can you confirm? ([ci build](https://github.com/p2sr/SourceAutoRecord/actions/runs/10758945613))

**Comment by rudkoLA** [comment]
yes works
