### ISSUE TITLE
`sar_hud_velang 2` for xyz velang 

### ISSUE THREAD

**Issue by rudkoLA** [p2sr/SourceAutoRecord#278]
Make velang count all axis' velocities if passed 2 as the argument

**Comment by ThisAMJ** [comment]
To clarify, you want `velang: -30.152 172.397` for example?

**Comment by rudkoLA** [comment]
yeah just angles you could setang to and be able to noclip forward and it would be the same as moving with that velocity continuously like in a voidclip chain

**Comment by ThisAMJ** [comment]
this is super simple to add but i'm waiting for @kot9pa16lvl to finish their hud changes or tell me they gave up or smn
