### ISSUE TITLE
`wait_persist_across_loads` does not work in INFRA

### ISSUE THREAD

**Issue by ontrigger** [p2sr/SourceAutoRecord#291]
repro steps: 
1. type `hwait 600 say xddddd`
2. `load_fast` any save on the same map
3. get xddddd on screen even though `wait_persist_across_loads` is 0

**Comment by ThisAMJ** [comment]
`hwait` is a different mechanism to `wait`, `wait_to`, and `wait_for`, just scheduling the command in x "host ticks" (which continue through loads)

**Comment by ontrigger** [comment]
Ah, I see, ty
