### ISSUE TITLE
[bug?] sar_hud_velocity_precision is protected by sv_cheats

### ISSUE THREAD

**Issue by AyumiToshiyuki** [p2sr/SourceAutoRecord#37]
If sv_cheats is zero, then sar_hud_velocity_precision is limited to 2, any value higher than that will default to 2.
I don't know if this is a bug or an intended feature, but i think up to 6 digits are allowed in runs, and sar_hud_precision doesn't have the same problem, so I don't think velocity should be limited to 2 digits.

**Comment by mlugg** [comment]
Sorry for slow response here - this is an intentional feature, there was a subtle change to the rules recently that limits the precision of velocity in the HUD to 2dp, because that's the highest precision you can achieve in the base game. Speak to Betsruner if you'd like a bit more info on that :)
