### ISSUE TITLE
can't load plugin in portal 2

### ISSUE THREAD

**Issue by Jannover5000r** [p2sr/SourceAutoRecord#41]
I can download and drop the plugin in the portal 2 folder just fine and it deosen't get deleted by my antivirus just to be sure i added the folder to the whitelist but when i start the game i can't use the "plugin_load sar" command and it gives me an error that it can't get loaded.
I tried to put it in the lowercase and uppercase "p" portal2 folder.
A restart of my pc isn't helping too and portal is running just fine without it.

**Comment by Jannover5000r** [comment]
Just to be save i downloaded the newest version now and it still gave me that error in the picture:
![Portal 2 Screenshot 2021 09 14 - 15 02 50 11](https://user-images.githubusercontent.com/90698896/133262711-d0ae0285-d1eb-4785-872f-a80598c834a4.png)

**Comment by mlugg** [comment]
That error means it can't open the file properly. Can you right-click on `sar.dll` and go to Properties, and send a screenshot of that window? It's possible your browser has marked the file as unsafe or something so isn't letting Portal 2 open it.

**Comment by Jannover5000r** [comment]
I hope that's the right window

![image](https://user-images.githubusercontent.com/90698896/133265326-87bf9a27-c97e-48f9-a6a8-1ab54d57cfac.png)

**Comment by mlugg** [comment]
Try ticking the "Unblock" box in that window, hitting OK, restarting Portal 2 and trying again

**Comment by Jannover5000r** [comment]
It's still giving me the same error

**Comment by PortalRex** [comment]
You have two drives and portal 2 on both please make sure you have sar in the correct drive as I can seen from the provided screenshots you're game is launched from your E drive while SAR is on your C drive.

**Comment by Jannover5000r** [comment]
> You have two drives and portal 2 on both please make sure you have sar in the correct drive as I can seen from the provided screenshots you're game is launched from your E drive while SAR is on your C drive.

thank you really much it works when i put it in the right folder i just didn't saw that i have it installed two times
