### ISSUE TITLE
[bug] running quit or exit while playing a demo crashes the game

### ISSUE THREAD

**Issue by mlugg** [p2sr/SourceAutoRecord#5]
Using quit during a demo will cause the game to hang up and not respond eventually crashing.
Exit will close the game but it is crashing.

Transferred from Blenderiste09/SourceAutoRecord#59

**Comment by PortalRex** [comment]
Fixed in 4af729c

**Comment by mlugg** [comment]
Hopefully fixed with recent changes that prevented SAR crashing the game on exit; needs retest
