### ISSUE TITLE
[bug] Setting sar_hud_font_index (and other font_index commands) to a number over the maximum crashes the game

### ISSUE THREAD

**Issue by kittsun** [p2sr/SourceAutoRecord#67]
Setting it to a number over 227 will crash the game. Should most likely return an error instead.

**Comment by mlugg** [comment]
This issue has been known about for a while, but it's not one that can really be properly dealt with. The values which crash the game are inconsistent between different platforms, and I think there are gaps (i.e. where X will crash the game but X+1 won't). We don't have an easy way to detect which font indices are valid, so I'm going to mark this as wontfix

**Comment by Krzyhau** [comment]
Issue fixed in [fix/fonts](/p2sr/SourceAutoRecord/tree/fix/fonts) branch for Windows - invalid font IDs are now properly detected and replaced with default font. Waiting for @mlugg to deal with Linux support and merge into master. Issue remains closed I guess.

**Comment by mlugg** [comment]
I guess I closed this prematurely lol - fixed by 686e6d3
