### ISSUE TITLE
[bug] TAS 'start map' doesn't work in Speedrun Mod

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/SourceAutoRecord#75]
E.g.
```
version 3
start map sp_a1_intro1
0>|||echo Hello???
```
Produces `Cannot activate TAS file - unknown map 'sp_a1_intro1.'`

Workaround:
Copy the contents of _**Portal 2/portal2/maps**_ to _**Portal 2 Speedrun Mod/maps**_

**Comment by Krzyhau** [comment]
Fixed for Windows. Waiting for someone with Linux to fix it on their platform lol.

**Comment by ThisAMJ** [comment]
Fixed for Linux with 39e8396
