### ISSUE TITLE
bug: missing newlines

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/SourceAutoRecord#76]
Help strings for the following commands have no newline:

- `sar_drawline`
- `sar_drawline_clear`
- `sar_trace_bbox_at`
- `sar_trace_bbox_ent_dist`
- `sar_trace_bbox_use_hover`

**Comment by Krzyhau** [comment]
[Fixed](https://github.com/p2sr/SourceAutoRecord/commit/ca7dd3c77a56598a89f0b51287780392d87d95ca).
