### ISSUE TITLE
Portal 2 crashes when loading a map

### ISSUE THREAD

**Issue by noruVitbar** [p2sr/SourceAutoRecord#77]
With `sar_fast_load_preset full` the game crashes if you try to load a map using the console command "map"
With `sar_fast_load_preset none` the issue doesnt occur.

**Comment by JaioCG** [comment]
dont use fast loads, then

**Comment by mlugg** [comment]
i have literally no idea what's going on here and it's a low-ish priority thing atm - try different load presets (normal, sla) and let me know which ones work and don't

**Comment by noruVitbar** [comment]
nvm sorry for wasting your time, restarting the game twice seemed to work, no idea what happned there.

**Comment by noruVitbar** [comment]
Double nevermind, it still occurs, its just kinda random.
For now the fix is to not use fast load

**Comment by PortalRex** [comment]
Cannot reproduce, tried 200 uses of the map command from both the menu and on another map. What SAR version are you on, and if you use srconfigs what version?

**Comment by noruVitbar** [comment]
Sar version: 1.12.7-pre7
Srconfig- 0.8.0

**Comment by PortalRex** [comment]
Are you in the menu or in game when the crash occurs?

**Comment by noruVitbar** [comment]
in game meno, sorry for delay
