### ISSUE TITLE
Bad trace teleport errors

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/SourceAutoRecord#79]
![Screenshot-2022-06-18,12-10-36](https://user-images.githubusercontent.com/69196954/174418781-83c3b75c-dd6e-4b07-aece-e8f31994d21b.png)

When printing the trace name to teleport to, it just says -8293260 instead of whatever you put. The same is true of `sar_trace_teleport_at`.

**Comment by Krzyhau** [comment]
Fixed in 4320cf132ae58c678ace9f38694039f9a827978b
