### ISSUE TITLE
plugin_load sar immediately crashes thestanleyparabledemo

### ISSUE THREAD

**Issue by wertercatt** [p2sr/SourceAutoRecord#81]
https://steamdb.info/app/247750/

When attempting to run SAR with the stanley.exe fork of portal2.exe, it crashes immediately.

**Comment by JaioCG** [comment]
This version of SAR has features specific to Portal 2. Even games that run on the same branch of Source like TSP won't work. 

If you want to use SAR in The Stanley Parable, use this old version before SAR went Portal 2-exclusive. `https://github.com/NeKzor/SourceAutoRecord/releases`

**Comment by wertercatt** [comment]
That one won't load either. Unfortunate, but fair enough.
