### ISSUE TITLE
[feature] Portals recorded in trace

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/SourceAutoRecord#83]
@RainbowwPhoenixx has this working locally afaik, just hasn't been pushed

There are also a couple considerations to take into account. Should there be a 'simple' rectangular mode? If so, will the carving rules for floor portals be implemented?

**Comment by RainbowwPhoenixx** [comment]
I have it locally however it is not complete, I fail to detect which the owner of the portals in coop

As for the rest, the answer is bot for now

**Comment by ThisAMJ** [comment]
Can't you find the portals by their linkage ids? Taking a look at the `portal_report` function you should be able to hook `CProp_Portal::FindPortal` (not sure if I'm allowed to post leak references here) (cough cough search `PortalReportFunc`)

**Comment by ThisAMJ** [comment]
Implemented in d96c2db, but I'm keeping this open until cvar to control shape is added

**Comment by ThisAMJ** [comment]
Portal shape cvar added in #88
