### ISSUE TITLE
sar_dpi_scale snaps view when disabled

### ISSUE THREAD

**Issue by Fibes1** [p2sr/SourceAutoRecord#87]
If you move your camera whilst having sar_dpi_scale set to anything above 1, your camera will snap to a seemingly random place when you set it back to 1, which is further away with higher values

https://user-images.githubusercontent.com/75185623/179394435-1fc76530-e60a-44ab-af14-3cb1a4f4b159.mp4

**Comment by mlugg** [comment]
So, what's going on here is the "residual" mouse movement that SAR has stored (which is part of the progress towards another dot) is being immediately applied. I can probably just kill this data when the cvar changes - I'll look into it hopefully later today
