### ISSUE TITLE
Autosplitter sometimes doesn't work

### ISSUE THREAD

**Issue by 5tr1k3r** [p2sr/SourceAutoRecord#9]
I'm using the newest beta version of SAR (1.12.3-pre1) and playing Portal Reloaded latest version (1.1.0) with LiveSplit and scriptable auto splitter, using `sar.asl`: [sar_asl.zip](https://github.com/p2sr/SourceAutoRecord/files/6445002/sar_asl.zip)

I have chamber splits that I took from https://www.speedrun.com/p2reloaded/resources

Lately more often than not autosplit doesn't get triggered, i saw it happen in chambers 3, 16, 21.
For example, here it didn't work upon finishing chamber 16, only firing when chamber 17 was done:
![image](https://user-images.githubusercontent.com/11004850/117522883-1f1cbc00-afcf-11eb-955d-adfeed3cc7de.png)

https://www.youtube.com/watch?v=Ozv-u7GSIXY - showcase of the bug
https://youtu.be/WXEe7ZYapn0?t=820 - timestamp for a successful autosplit in the other run, to show where it should have happened

**Comment by 5tr1k3r** [comment]
Adding one more example of this happening.
https://www.youtube.com/watch?v=mp2zB4mrjbQ here autosplit should have been at 0:20 but happened at 1:34, after finishing the next chamber
https://youtu.be/WXEe7ZYapn0?t=155 how it works normally

**Comment by mlugg** [comment]
Fixed in af872d1
