### ISSUE TITLE
[feature] 'move' TAS tool

### ISSUE THREAD

**Issue by ThisAMJ** [p2sr/SourceAutoRecord#91]
This has been suggested before, but I hope to quantify the requirements.

`>>move [nocam|veccam] [xdeg] [xups] [nopitchlock] [nojump] [letspeedlock]`

- Veccam camera by default (I still think smoothing is better than giving up when you reach a straight line) unless of course you're on speed gel
- Camera should initially move with constant ~~speed~~ angular velocity? to reach vel angle instead of instantly
- Absmov on ground until strafe is faster
- Take into account duckstate
- Autojump w duck when it is faster, unless nojump
- Apply pitchlock whenever moving in air, not just strafing
- Switch to ang strafing on speed gel
- Avoid the 150-150 cap when possible, using the same `letspeedlock` optional arg
- If above target velocity, decel w no autojump until under, then return to regular behaviour

lmk if ive forgotten stuff or are being unreasonable

**Comment by Krzyhau** [comment]
As it was discussed in a TASing Discord server once, majority of points is an attempt to simplify a case, which not always would benefit from being generalized. I'll call it a `finish game` tool syndrome - tools should be simplified to allow the easiest user experience, but on the other hand discouraging users from having control can lead to unoptimized runs.

Here are some additional points:
 - maybe an additional camera mode for interpolating into current vel would be useful sometimes. But considering that it'd be used only to make TASes more visually pleasing (which you can already do by just adding a quick setang a few ticks before strafing), and there isn't that high demand for it, I don't find it necessary.
 - not sure what you mean by "taking duckstate into account". Strafing already detects you being grounded and adjusts calculations to that.
 - autostrafer was already programmed to just move towards desired angles if velocity is too low, but that behaviour never functioned properly. Version 6 hopefully fixes it.

Closing the issue.
